### ISSUE TITLE
Jupyter Lab Command

### ISSUE THREAD

**Issue by VCSocial** [drmaj/AI-ML-Docker-Setup#2]
To run Jupyter lab the commands:
```
$ jupyter lab --ip=*
$ jupyter lab
```
do not work. To get it running I had to issue the command:
```
$ jupyter notebook --allow-root --ip 127.0.0.1
```
This was tested on an Ubuntu 18.04 host.

**Comment by ghost** [comment]
you can also run

`$ jupyer lab --ip=0.0.0.0`
